/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/R2axIWy95x4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
export function GameScreen() {
  return (
    <div className="max-w-screen mx-auto p-4 bg-white h-screen">
      <div className="flex justify-between items-center mb-6">
        <div className="flex space-x-2">
          <HeartIcon className="w-6 h-6 text-red-500" />
          <HeartIcon className="w-6 h-6 text-red-500" />
          <HeartIcon className="w-6 h-6 text-red-500" />
        </div>
        <div className="flex space-x-4">
          {/* <div className="bg-gray-200 px-4 py-1">Potential</div>
          <div className="bg-gray-200 px-4 py-1">Stats</div> */}
          <SettingsIcon className="w-6 h-6 text-gray-600" />
        </div>
      </div>
      <div className="grid grid-cols-2 gap-4 mb-4">
        <div className="bg-gray-100 p-4">
          <p className="text-lg font-semibold text-black">The journey begins with a single step...</p>
        </div>
        <div className="bg-gray-100 p-4">
          <img
            alt="Placeholder image"
            className="mb-2"
            height="auto"
            src="/placeholder.svg"
            style={{
              maxWidth: "100%",
              height: "auto",
              objectFit: "cover",
            }}
            width="100%"
          />
          <p className="text-lg font-semibold text-black"> Image </p>
        </div>
      </div>
      <div className="flex justify-center space-x-2 mt-6">
        <Button className="black px-12 py-3">Option A</Button>
        <Button className="black px-12 py-3">Option B</Button>
        <Button className="black px-12 py-3">Option C</Button>
      </div>
    </div>
  )
}

interface HeartIconProps {
  [key: string]: any;
}

function HeartIcon(props: HeartIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>
  )
}

interface SettingsIconProps {
  [key: string]: any;
}

function SettingsIcon(props: SettingsIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}
